### PR TITLE
Using generics to use u8, u16, u32, u64 and usize + Removing the most warnings

### PR DESCRIPTION
**Pull request by Tockra**

### CODE REVIEW

**Review by JMurph2015 — APPROVED** [review]
Looks good to me

**Review by JMurph2015 — COMMENTED** [review]
Needs a version bump on `Cargo.toml` though.

**Comment by Tockra** [comment]
Then you need to do it. After 2 years I have no idea what this issue is about ...

**Comment by Tockra** [comment]
I'm sorry but this PR is so old, I have no idea what it is about and I already removed the corresponding repository.

**Pull request closed without merging**
